version: "3.8"

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: calorie-checker-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - /app/__pycache__
    restart: unless-stopped
    networks:
      - calorie-network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: calorie-checker-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - calorie-network

networks:
  calorie-network:
    driver: bridge

volumes:
  backend_data:
